'use client';

import Link from 'next/link';
import { Edit3, Loader2, Mic2, Plus, Search, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { useAuth } from '@/components/providers/auth-provider';
import { createDocument, removeDocument, updateDocument } from '@/lib/firestore';
import { uploadToCloudinary } from '@/lib/cloudinary-client';
import type { Artist } from '@/lib/types';
import { ArtistAvatar } from '@/components/ui/artist-avatar';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { FileDropzone } from '@/components/ui/file-dropzone';
import { AdminCard, AdminGuard, AdminHeading, FormField, inputClass, textareaClass, useAdminCollection } from '@/components/admin/admin-shared';

export function ArtistManagerPage() { return <AdminGuard><ArtistManager /></AdminGuard>; }

function ArtistManager() {
  const { user } = useAuth();
  const { items, loading, error } = useAdminCollection<Artist & Record<string, unknown>>('artists');
  const [search, setSearch] = useState('');
  const [editing, setEditing] = useState<Artist | undefined>();
  const [open, setOpen] = useState(false);
  const [deleting, setDeleting] = useState<Artist | undefined>();
  const filtered = useMemo(() => items.filter((artist) => `${artist.name} ${artist.genre || ''}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [items, search]);
  const removeArtist = async () => { if (!deleting) return; try { await removeDocument('artists', deleting.id); toast.success('Artist profile deleted.'); } catch { toast.error('Could not delete the artist.'); } finally { setDeleting(undefined); } };
  return <div className="space-y-7"><AdminHeading title="Artists" description="Build the artist profiles that give every release a home." action={<button type="button" onClick={() => { setEditing(undefined); setOpen(true); }} className="inline-flex items-center gap-2 rounded-full bg-gold px-4 py-2.5 text-xs font-semibold text-black hover:bg-gold-bright"><Plus className="h-3.5 w-3.5" />Add artist</button>} /><AdminCard className="p-3"><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-3"><Search className="h-4 w-4 text-white/30" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search artist profiles" className="h-10 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/25" /></div></AdminCard>{error && <p className="rounded-xl border border-red-300/20 bg-red-400/10 px-4 py-3 text-xs text-red-200">Could not read artist profiles: {error}</p>}<AdminCard>{loading ? <p className="p-6 text-sm text-white/40">Loading artist profiles…</p> : filtered.length ? <div className="grid gap-1 divide-y divide-white/[.06] md:divide-y-0">{filtered.map((artist) => <div key={artist.id} className="flex items-center gap-4 px-4 py-4 transition hover:bg-white/[.025] md:px-5"><ArtistAvatar name={artist.name} src={artist.profileImage} size="md" /><div className="min-w-0 flex-1"><Link href={`/artist/${artist.id}`} className="block truncate text-sm font-semibold text-white hover:text-gold">{artist.name}</Link><p className="mt-1 truncate text-xs text-white/35">{artist.genre || 'Genre not set'}{artist.biography ? ` · ${artist.biography}` : ''}</p></div><div className="flex items-center gap-1"><button type="button" onClick={() => { setEditing(artist); setOpen(true); }} className="rounded-lg p-2 text-white/35 hover:bg-gold/10 hover:text-gold" aria-label={`Edit ${artist.name}`}><Edit3 className="h-4 w-4" /></button><button type="button" onClick={() => setDeleting(artist)} className="rounded-lg p-2 text-white/30 hover:bg-red-400/10 hover:text-red-300" aria-label={`Delete ${artist.name}`}><Trash2 className="h-4 w-4" /></button></div></div>)}</div> : <div className="px-5 py-16 text-center"><Mic2 className="mx-auto h-8 w-8 text-white/20" /><p className="mt-3 text-sm text-white/40">{search ? 'No artist profiles match.' : 'No artist profiles yet.'}</p></div>}</AdminCard><ArtistEditor open={open} artist={editing} onClose={() => setOpen(false)} onSaved={() => setOpen(false)} /><ConfirmDialog open={Boolean(deleting)} title="Delete this artist?" description={`The profile for “${deleting?.name}” will be deleted. Songs that reference it will keep their saved artist name.`} onClose={() => setDeleting(undefined)} onConfirm={() => void removeArtist()} /></div>;
}

function ArtistEditor({ open, artist, onClose, onSaved }: { open: boolean; artist?: Artist; onClose: () => void; onSaved: () => void }) {
  const { user } = useAuth();
  const [name, setName] = useState('');
  const [genre, setGenre] = useState('');
  const [biography, setBiography] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [imageUrl, setImageUrl] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setName(artist?.name || ''); setGenre(artist?.genre || ''); setBiography(artist?.biography || ''); setImageUrl(artist?.profileImage || ''); setFile(null); } }, [open, artist]);
  if (!open) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!user || !name.trim()) { toast.error('Artist name is required.'); return; } setSaving(true); try { let profileImage = imageUrl; let profileImagePublicId = (artist as Artist & { profileImagePublicId?: string })?.profileImagePublicId; if (file) { if (file.size > 10 * 1024 * 1024) throw new Error('Profile image must be smaller than 10 MB.'); const result = await uploadToCloudinary(file, 'simz-naxty/artists', await user.getIdToken()); profileImage = result.secure_url; profileImagePublicId = result.public_id; } const data = { name: name.trim(), genre: genre.trim(), biography: biography.trim(), profileImage, profileImagePublicId, updatedAt: new Date().toISOString() }; if (artist) await updateDocument('artists', artist.id, data); else await createDocument('artists', { ...data, createdAt: new Date().toISOString() }); toast.success(artist ? 'Artist profile updated.' : 'Artist profile created.'); onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not save the artist.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-black/80 p-3 backdrop-blur-sm sm:p-6"><div className="mx-auto max-w-2xl rounded-3xl border border-white/10 bg-[#151515] shadow-2xl"><div className="flex items-center justify-between border-b border-white/[.08] px-5 py-4 sm:px-7"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-gold/75">Artist studio</p><h2 className="mt-1 font-display text-xl font-semibold text-white">{artist ? 'Edit artist' : 'Create artist profile'}</h2></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-white/40 hover:bg-white/10 hover:text-white" aria-label="Close"><X className="h-5 w-5" /></button></div><form onSubmit={submit} className="space-y-5 p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><FormField label="Name"><input required value={name} onChange={(event) => setName(event.target.value)} className={inputClass} placeholder="Artist name" /></FormField><FormField label="Genre"><input value={genre} onChange={(event) => setGenre(event.target.value)} className={inputClass} placeholder="e.g. Hip-hop" /></FormField></div><FormField label="Biography"><textarea value={biography} onChange={(event) => setBiography(event.target.value)} className={`${textareaClass} min-h-[150px]`} placeholder="Tell listeners about this artist" /></FormField><FormField label="Profile image" hint="Optional. JPG, PNG or WEBP up to 10 MB."><FileDropzone accept="image/jpeg,image/png,image/webp" label="Choose a profile image" hint="Upload to Cloudinary" type="image" file={file} onChange={setFile} />{imageUrl && !file && <p className="mt-2 text-[10px] text-emerald-300/60">Existing profile image is attached.</p>}</FormField><div className="flex justify-end gap-2 border-t border-white/[.08] pt-5"><button type="button" onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-semibold text-white/55 hover:bg-white/[.05]">Cancel</button><button type="submit" disabled={saving} className="inline-flex min-w-[130px] items-center justify-center gap-2 rounded-xl bg-gold px-4 py-2.5 text-xs font-semibold text-black hover:bg-gold-bright disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{saving ? 'Saving…' : artist ? 'Save changes' : 'Create profile'}</button></div></form></div></div>;
}
