'use client';

import { Shield, UserRound, Users } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/components/providers/auth-provider';
import { updateDocument } from '@/lib/firestore';
import type { AppUser, UserRole } from '@/lib/types';
import { formatDate } from '@/lib/utils';
import { AdminCard, AdminGuard, AdminHeading, useAdminCollection } from '@/components/admin/admin-shared';

export function UserManagerPage() { return <AdminGuard><UserManager /></AdminGuard>; }
function UserManager() {
  const { user } = useAuth();
  const { items, loading, error } = useAdminCollection<AppUser & Record<string, unknown>>('users');
  const setRole = async (profile: AppUser, role: UserRole) => { if (profile.role === role) return; try { await updateDocument('users', profile.id, { role }); toast.success(`${profile.displayName || profile.email} is now ${role}.`); } catch { toast.error('Could not update this user role.'); } };
  return <div className="space-y-7"><AdminHeading title="Users" description="Review accounts and manage trusted workspace access." /><div className="grid gap-4 sm:grid-cols-3"><MiniStat icon={Users} value={items.length} label="registered users" /><MiniStat icon={Shield} value={items.filter((item) => item.role === 'admin').length} label="administrators" /><MiniStat icon={UserRound} value={items.filter((item) => item.role !== 'admin').length} label="listeners" /></div><AdminCard>{error && <p className="border-b border-red-300/20 bg-red-400/10 px-5 py-3 text-xs text-red-200">Could not read users: {error}</p>}{loading ? <p className="p-6 text-sm text-white/40">Loading users…</p> : items.length ? <div className="divide-y divide-white/[.06]">{items.map((profile) => <div key={profile.id} className="flex flex-wrap items-center gap-3 px-4 py-4 md:px-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-gold/20 bg-gold/10 font-display text-sm font-semibold text-gold">{(profile.displayName || profile.email || 'SN').slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-white">{profile.displayName || 'Unnamed listener'}{profile.id === user?.uid && <span className="ml-2 text-[10px] text-gold">You</span>}</p><p className="mt-1 truncate text-xs text-white/35">{profile.email} · joined {formatDate(profile.createdAt)}</p></div><span className={profile.role === 'admin' ? 'rounded-full bg-gold/10 px-2.5 py-1 text-[10px] font-semibold text-gold' : 'rounded-full bg-white/[.07] px-2.5 py-1 text-[10px] text-white/45'}>{profile.role}</span><select value={profile.role} onChange={(event) => void setRole(profile, event.target.value as UserRole)} className="h-9 rounded-lg border border-white/10 bg-[#171717] px-2 text-xs text-white/60 outline-none focus:border-gold/40"><option value="user">User</option><option value="admin">Admin</option></select></div>)}</div> : <div className="px-5 py-16 text-center"><Users className="mx-auto h-8 w-8 text-white/20" /><p className="mt-3 text-sm text-white/40">No user profiles yet.</p></div>}</AdminCard><p className="text-[11px] leading-5 text-white/25">Role changes are protected by Firestore rules. API routes also verify the Firebase ID token and server-side profile before issuing media signatures.</p></div>;
}
function MiniStat({ icon: Icon, value, label }: { icon: React.ComponentType<{ className?: string }>; value: number; label: string }) { return <AdminCard className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/[.06] text-white/55"><Icon className="h-4 w-4" /></span><div><p className="font-display text-xl font-semibold text-white">{value}</p><p className="text-[10px] text-white/35">{label}</p></div></AdminCard>; }
